import triton

_TUNED_CONFIGS = {
    "CUTENSOR_OP_IDENTITY": [
        triton.Config({"BLOCK_SIZE": 256, "BLOCKS_PER_PROGRAM": 1}, num_warps=2),
        triton.Config({"BLOCK_SIZE": 256, "BLOCKS_PER_PROGRAM": 2}, num_warps=4),
        triton.Config({"BLOCK_SIZE": 512, "BLOCKS_PER_PROGRAM": 1}, num_warps=4),
        triton.Config({"BLOCK_SIZE": 512, "BLOCKS_PER_PROGRAM": 2}, num_warps=4),
        triton.Config({"BLOCK_SIZE": 1024, "BLOCKS_PER_PROGRAM": 1}, num_warps=8),
        triton.Config({"BLOCK_SIZE": 1024, "BLOCKS_PER_PROGRAM": 2}, num_warps=8),
        triton.Config({"BLOCK_SIZE": 1024, "BLOCKS_PER_PROGRAM": 4}, num_warps=8),
    ],
    "CUTENSOR_OP_SQRT": [
        triton.Config({"BLOCK_SIZE": 256, "BLOCKS_PER_PROGRAM": 1}, num_warps=2),
        triton.Config({"BLOCK_SIZE": 256, "BLOCKS_PER_PROGRAM": 2}, num_warps=4),
        triton.Config({"BLOCK_SIZE": 512, "BLOCKS_PER_PROGRAM": 1}, num_warps=4),
        triton.Config({"BLOCK_SIZE": 512, "BLOCKS_PER_PROGRAM": 2}, num_warps=4),
        triton.Config({"BLOCK_SIZE": 1024, "BLOCKS_PER_PROGRAM": 1}, num_warps=8),
        triton.Config({"BLOCK_SIZE": 1024, "BLOCKS_PER_PROGRAM": 2}, num_warps=8),
        triton.Config({"BLOCK_SIZE": 1024, "BLOCKS_PER_PROGRAM": 4}, num_warps=8),
    ],
    "CUTENSOR_OP_RELU": [
        triton.Config({"BLOCK_SIZE": 256, "BLOCKS_PER_PROGRAM": 1}, num_warps=2),
        triton.Config({"BLOCK_SIZE": 256, "BLOCKS_PER_PROGRAM": 2}, num_warps=4),
        triton.Config({"BLOCK_SIZE": 512, "BLOCKS_PER_PROGRAM": 1}, num_warps=4),
        triton.Config({"BLOCK_SIZE": 512, "BLOCKS_PER_PROGRAM": 2}, num_warps=4),
        triton.Config({"BLOCK_SIZE": 1024, "BLOCKS_PER_PROGRAM": 1}, num_warps=8),
        triton.Config({"BLOCK_SIZE": 1024, "BLOCKS_PER_PROGRAM": 2}, num_warps=8),
        triton.Config({"BLOCK_SIZE": 1024, "BLOCKS_PER_PROGRAM": 4}, num_warps=8),
    ],
    "CUTENSOR_OP_CONJ": [
        triton.Config({"BLOCK_SIZE": 256, "BLOCKS_PER_PROGRAM": 1}, num_warps=2),
        triton.Config({"BLOCK_SIZE": 256, "BLOCKS_PER_PROGRAM": 2}, num_warps=4),
        triton.Config({"BLOCK_SIZE": 512, "BLOCKS_PER_PROGRAM": 1}, num_warps=4),
        triton.Config({"BLOCK_SIZE": 512, "BLOCKS_PER_PROGRAM": 2}, num_warps=4),
        triton.Config({"BLOCK_SIZE": 1024, "BLOCKS_PER_PROGRAM": 1}, num_warps=8),
        triton.Config({"BLOCK_SIZE": 1024, "BLOCKS_PER_PROGRAM": 2}, num_warps=8),
        triton.Config({"BLOCK_SIZE": 1024, "BLOCKS_PER_PROGRAM": 4}, num_warps=8),
    ],
    "CUTENSOR_OP_RCP": [
        triton.Config({"BLOCK_SIZE": 256, "BLOCKS_PER_PROGRAM": 1}, num_warps=2),
        triton.Config({"BLOCK_SIZE": 256, "BLOCKS_PER_PROGRAM": 2}, num_warps=4),
        triton.Config({"BLOCK_SIZE": 512, "BLOCKS_PER_PROGRAM": 1}, num_warps=4),
        triton.Config({"BLOCK_SIZE": 512, "BLOCKS_PER_PROGRAM": 2}, num_warps=4),
        triton.Config({"BLOCK_SIZE": 1024, "BLOCKS_PER_PROGRAM": 1}, num_warps=8),
        triton.Config({"BLOCK_SIZE": 1024, "BLOCKS_PER_PROGRAM": 2}, num_warps=8),
        triton.Config({"BLOCK_SIZE": 1024, "BLOCKS_PER_PROGRAM": 4}, num_warps=8),
    ],
    "CUTENSOR_OP_SIGMOID": [
        triton.Config({"BLOCK_SIZE": 256, "BLOCKS_PER_PROGRAM": 1}, num_warps=2),
        triton.Config({"BLOCK_SIZE": 256, "BLOCKS_PER_PROGRAM": 2}, num_warps=4),
        triton.Config({"BLOCK_SIZE": 512, "BLOCKS_PER_PROGRAM": 1}, num_warps=4),
        triton.Config({"BLOCK_SIZE": 512, "BLOCKS_PER_PROGRAM": 2}, num_warps=4),
        triton.Config({"BLOCK_SIZE": 1024, "BLOCKS_PER_PROGRAM": 1}, num_warps=8),
        triton.Config({"BLOCK_SIZE": 1024, "BLOCKS_PER_PROGRAM": 2}, num_warps=8),
        triton.Config({"BLOCK_SIZE": 1024, "BLOCKS_PER_PROGRAM": 4}, num_warps=8),
    ],
    "CUTENSOR_OP_TANH": [
        triton.Config({"BLOCK_SIZE": 256, "BLOCKS_PER_PROGRAM": 1}, num_warps=2),
        triton.Config({"BLOCK_SIZE": 256, "BLOCKS_PER_PROGRAM": 2}, num_warps=4),
        triton.Config({"BLOCK_SIZE": 512, "BLOCKS_PER_PROGRAM": 1}, num_warps=4),
        triton.Config({"BLOCK_SIZE": 512, "BLOCKS_PER_PROGRAM": 2}, num_warps=4),
        triton.Config({"BLOCK_SIZE": 1024, "BLOCKS_PER_PROGRAM": 1}, num_warps=8),
        triton.Config({"BLOCK_SIZE": 1024, "BLOCKS_PER_PROGRAM": 2}, num_warps=8),
        triton.Config({"BLOCK_SIZE": 1024, "BLOCKS_PER_PROGRAM": 4}, num_warps=8),
    ],
    "CUTENSOR_OP_ABS": [
        triton.Config({"BLOCK_SIZE": 256, "BLOCKS_PER_PROGRAM": 1}, num_warps=2),
        triton.Config({"BLOCK_SIZE": 256, "BLOCKS_PER_PROGRAM": 2}, num_warps=4),
        triton.Config({"BLOCK_SIZE": 512, "BLOCKS_PER_PROGRAM": 1}, num_warps=4),
        triton.Config({"BLOCK_SIZE": 512, "BLOCKS_PER_PROGRAM": 2}, num_warps=4),
        triton.Config({"BLOCK_SIZE": 1024, "BLOCKS_PER_PROGRAM": 1}, num_warps=8),
        triton.Config({"BLOCK_SIZE": 1024, "BLOCKS_PER_PROGRAM": 2}, num_warps=8),
        triton.Config({"BLOCK_SIZE": 1024, "BLOCKS_PER_PROGRAM": 4}, num_warps=8),
    ],
    "CUTENSOR_OP_NEG": [
        triton.Config({"BLOCK_SIZE": 256, "BLOCKS_PER_PROGRAM": 1}, num_warps=2),
        triton.Config({"BLOCK_SIZE": 256, "BLOCKS_PER_PROGRAM": 2}, num_warps=4),
        triton.Config({"BLOCK_SIZE": 512, "BLOCKS_PER_PROGRAM": 1}, num_warps=4),
        triton.Config({"BLOCK_SIZE": 512, "BLOCKS_PER_PROGRAM": 2}, num_warps=4),
        triton.Config({"BLOCK_SIZE": 1024, "BLOCKS_PER_PROGRAM": 1}, num_warps=8),
        triton.Config({"BLOCK_SIZE": 1024, "BLOCKS_PER_PROGRAM": 2}, num_warps=8),
        triton.Config({"BLOCK_SIZE": 1024, "BLOCKS_PER_PROGRAM": 4}, num_warps=8),
    ],
    "CUTENSOR_OP_SIN": [
        triton.Config({"BLOCK_SIZE": 256, "BLOCKS_PER_PROGRAM": 1}, num_warps=2),
        triton.Config({"BLOCK_SIZE": 256, "BLOCKS_PER_PROGRAM": 2}, num_warps=4),
        triton.Config({"BLOCK_SIZE": 512, "BLOCKS_PER_PROGRAM": 1}, num_warps=4),
        triton.Config({"BLOCK_SIZE": 512, "BLOCKS_PER_PROGRAM": 2}, num_warps=4),
        triton.Config({"BLOCK_SIZE": 1024, "BLOCKS_PER_PROGRAM": 1}, num_warps=8),
        triton.Config({"BLOCK_SIZE": 1024, "BLOCKS_PER_PROGRAM": 2}, num_warps=8),
        triton.Config({"BLOCK_SIZE": 1024, "BLOCKS_PER_PROGRAM": 4}, num_warps=8),
    ],
    "CUTENSOR_OP_COS": [
        triton.Config({"BLOCK_SIZE": 256, "BLOCKS_PER_PROGRAM": 1}, num_warps=2),
        triton.Config({"BLOCK_SIZE": 256, "BLOCKS_PER_PROGRAM": 2}, num_warps=4),
        triton.Config({"BLOCK_SIZE": 512, "BLOCKS_PER_PROGRAM": 1}, num_warps=4),
        triton.Config({"BLOCK_SIZE": 512, "BLOCKS_PER_PROGRAM": 2}, num_warps=4),
        triton.Config({"BLOCK_SIZE": 1024, "BLOCKS_PER_PROGRAM": 1}, num_warps=8),
        triton.Config({"BLOCK_SIZE": 1024, "BLOCKS_PER_PROGRAM": 2}, num_warps=8),
        triton.Config({"BLOCK_SIZE": 1024, "BLOCKS_PER_PROGRAM": 4}, num_warps=8),
    ],
    "CUTENSOR_OP_TAN": [
        triton.Config({"BLOCK_SIZE": 256, "BLOCKS_PER_PROGRAM": 1}, num_warps=2),
        triton.Config({"BLOCK_SIZE": 256, "BLOCKS_PER_PROGRAM": 2}, num_warps=4),
        triton.Config({"BLOCK_SIZE": 512, "BLOCKS_PER_PROGRAM": 1}, num_warps=4),
        triton.Config({"BLOCK_SIZE": 512, "BLOCKS_PER_PROGRAM": 2}, num_warps=4),
        triton.Config({"BLOCK_SIZE": 1024, "BLOCKS_PER_PROGRAM": 1}, num_warps=8),
        triton.Config({"BLOCK_SIZE": 1024, "BLOCKS_PER_PROGRAM": 2}, num_warps=8),
        triton.Config({"BLOCK_SIZE": 1024, "BLOCKS_PER_PROGRAM": 4}, num_warps=8),
    ],
    "CUTENSOR_OP_SINH": [
        triton.Config({"BLOCK_SIZE": 256, "BLOCKS_PER_PROGRAM": 1}, num_warps=2),
        triton.Config({"BLOCK_SIZE": 256, "BLOCKS_PER_PROGRAM": 2}, num_warps=4),
        triton.Config({"BLOCK_SIZE": 512, "BLOCKS_PER_PROGRAM": 1}, num_warps=4),
        triton.Config({"BLOCK_SIZE": 512, "BLOCKS_PER_PROGRAM": 2}, num_warps=4),
        triton.Config({"BLOCK_SIZE": 1024, "BLOCKS_PER_PROGRAM": 1}, num_warps=8),
        triton.Config({"BLOCK_SIZE": 1024, "BLOCKS_PER_PROGRAM": 2}, num_warps=8),
        triton.Config({"BLOCK_SIZE": 1024, "BLOCKS_PER_PROGRAM": 4}, num_warps=8),
    ],
    "CUTENSOR_OP_COSH": [
        triton.Config({"BLOCK_SIZE": 256, "BLOCKS_PER_PROGRAM": 1}, num_warps=2),
        triton.Config({"BLOCK_SIZE": 256, "BLOCKS_PER_PROGRAM": 2}, num_warps=4),
        triton.Config({"BLOCK_SIZE": 512, "BLOCKS_PER_PROGRAM": 1}, num_warps=4),
        triton.Config({"BLOCK_SIZE": 512, "BLOCKS_PER_PROGRAM": 2}, num_warps=4),
        triton.Config({"BLOCK_SIZE": 1024, "BLOCKS_PER_PROGRAM": 1}, num_warps=8),
        triton.Config({"BLOCK_SIZE": 1024, "BLOCKS_PER_PROGRAM": 2}, num_warps=8),
        triton.Config({"BLOCK_SIZE": 1024, "BLOCKS_PER_PROGRAM": 4}, num_warps=8),
    ],
    "CUTENSOR_OP_ASIN": [
        triton.Config({"BLOCK_SIZE": 256, "BLOCKS_PER_PROGRAM": 1}, num_warps=2),
        triton.Config({"BLOCK_SIZE": 256, "BLOCKS_PER_PROGRAM": 2}, num_warps=4),
        triton.Config({"BLOCK_SIZE": 512, "BLOCKS_PER_PROGRAM": 1}, num_warps=4),
        triton.Config({"BLOCK_SIZE": 512, "BLOCKS_PER_PROGRAM": 2}, num_warps=4),
        triton.Config({"BLOCK_SIZE": 1024, "BLOCKS_PER_PROGRAM": 1}, num_warps=8),
        triton.Config({"BLOCK_SIZE": 1024, "BLOCKS_PER_PROGRAM": 2}, num_warps=8),
        triton.Config({"BLOCK_SIZE": 1024, "BLOCKS_PER_PROGRAM": 4}, num_warps=8),
    ],
    "CUTENSOR_OP_ACOS": [
        triton.Config({"BLOCK_SIZE": 256, "BLOCKS_PER_PROGRAM": 1}, num_warps=2),
        triton.Config({"BLOCK_SIZE": 256, "BLOCKS_PER_PROGRAM": 2}, num_warps=4),
        triton.Config({"BLOCK_SIZE": 512, "BLOCKS_PER_PROGRAM": 1}, num_warps=4),
        triton.Config({"BLOCK_SIZE": 512, "BLOCKS_PER_PROGRAM": 2}, num_warps=4),
        triton.Config({"BLOCK_SIZE": 1024, "BLOCKS_PER_PROGRAM": 1}, num_warps=8),
        triton.Config({"BLOCK_SIZE": 1024, "BLOCKS_PER_PROGRAM": 2}, num_warps=8),
        triton.Config({"BLOCK_SIZE": 1024, "BLOCKS_PER_PROGRAM": 4}, num_warps=8),
    ],
    "CUTENSOR_OP_ATAN": [
        triton.Config({"BLOCK_SIZE": 256, "BLOCKS_PER_PROGRAM": 1}, num_warps=2),
        triton.Config({"BLOCK_SIZE": 256, "BLOCKS_PER_PROGRAM": 2}, num_warps=4),
        triton.Config({"BLOCK_SIZE": 512, "BLOCKS_PER_PROGRAM": 1}, num_warps=4),
        triton.Config({"BLOCK_SIZE": 512, "BLOCKS_PER_PROGRAM": 2}, num_warps=4),
        triton.Config({"BLOCK_SIZE": 1024, "BLOCKS_PER_PROGRAM": 1}, num_warps=8),
        triton.Config({"BLOCK_SIZE": 1024, "BLOCKS_PER_PROGRAM": 2}, num_warps=8),
        triton.Config({"BLOCK_SIZE": 1024, "BLOCKS_PER_PROGRAM": 4}, num_warps=8),
    ],
    "CUTENSOR_OP_ASINH": [
        triton.Config({"BLOCK_SIZE": 256, "BLOCKS_PER_PROGRAM": 1}, num_warps=2),
        triton.Config({"BLOCK_SIZE": 256, "BLOCKS_PER_PROGRAM": 2}, num_warps=4),
        triton.Config({"BLOCK_SIZE": 512, "BLOCKS_PER_PROGRAM": 1}, num_warps=4),
        triton.Config({"BLOCK_SIZE": 512, "BLOCKS_PER_PROGRAM": 2}, num_warps=4),
        triton.Config({"BLOCK_SIZE": 1024, "BLOCKS_PER_PROGRAM": 1}, num_warps=8),
        triton.Config({"BLOCK_SIZE": 1024, "BLOCKS_PER_PROGRAM": 2}, num_warps=8),
        triton.Config({"BLOCK_SIZE": 1024, "BLOCKS_PER_PROGRAM": 4}, num_warps=8),
    ],
    "CUTENSOR_OP_ACOSH": [
        triton.Config({"BLOCK_SIZE": 256, "BLOCKS_PER_PROGRAM": 1}, num_warps=2),
        triton.Config({"BLOCK_SIZE": 256, "BLOCKS_PER_PROGRAM": 2}, num_warps=4),
        triton.Config({"BLOCK_SIZE": 512, "BLOCKS_PER_PROGRAM": 1}, num_warps=4),
        triton.Config({"BLOCK_SIZE": 512, "BLOCKS_PER_PROGRAM": 2}, num_warps=4),
        triton.Config({"BLOCK_SIZE": 1024, "BLOCKS_PER_PROGRAM": 1}, num_warps=8),
        triton.Config({"BLOCK_SIZE": 1024, "BLOCKS_PER_PROGRAM": 2}, num_warps=8),
        triton.Config({"BLOCK_SIZE": 1024, "BLOCKS_PER_PROGRAM": 4}, num_warps=8),
    ],
    "CUTENSOR_OP_ATANH": [
        triton.Config({"BLOCK_SIZE": 256, "BLOCKS_PER_PROGRAM": 1}, num_warps=2),
        triton.Config({"BLOCK_SIZE": 256, "BLOCKS_PER_PROGRAM": 2}, num_warps=4),
        triton.Config({"BLOCK_SIZE": 512, "BLOCKS_PER_PROGRAM": 1}, num_warps=4),
        triton.Config({"BLOCK_SIZE": 512, "BLOCKS_PER_PROGRAM": 2}, num_warps=4),
        triton.Config({"BLOCK_SIZE": 1024, "BLOCKS_PER_PROGRAM": 1}, num_warps=8),
        triton.Config({"BLOCK_SIZE": 1024, "BLOCKS_PER_PROGRAM": 2}, num_warps=8),
        triton.Config({"BLOCK_SIZE": 1024, "BLOCKS_PER_PROGRAM": 4}, num_warps=8),
    ],
}


def get_tuned_config(op_name: str):
    if op_name not in _TUNED_CONFIGS:
        raise KeyError(f"No tuned config registered for op: {op_name}")
    return _TUNED_CONFIGS[op_name]


__all__ = ["get_tuned_config"]
